version: "3.8"

services:
  chunker:
    build:
      context: .
      dockerfile: Dockerfile
    image: video-processor-service
    environment:
      - REDIS_HOST=host.docker.internal
    volumes:
      - /Users/atharvamalji/IU/Spring 2025/ECC/clipcrunch/backend/processed_videos:/app/processed_videos
      - /Users/atharvamalji/IU/Spring 2025/ECC/clipcrunch/backend/processed_chunks:/app/processed_chunks
    deploy:
      replicas: 5
    restart: unless-stopped
